### ISSUE TITLE
How can I access score for fetched results

### ISSUE THREAD

**Issue by Sidd27** [VassilisPallas/mongoose-fuzzy-searching#14]

**Comment by VassilisPallas** [comment]
Since version`1.0.5` each object has a key named `textScore` which contains the score. Also in version `1.1.0` added a sorting based on the score.

https://github.com/VassilisPallas/mongoose-fuzzy-searching/blob/master/index.js#L270

**Comment by jomho** [comment]
If you are like me `confidenceScore` wasn't part of my schema so I had to access the private `_doc` object. This can be unintuitive if you are using `console.log(docs)`.

For example.
```
const docs = await Song.fuzzySearch(term)
docs[0]._doc.confidenceScore
```
