### ISSUE TITLE
No Error, no Results when setting other searchfields 

### ISSUE THREAD

**Issue by EliasPh** [VassilisPallas/mongoose-fuzzy-searching#18]
Hey, 
this seems to be more of an implementation problem but anyway:
Using your example code works fine, but when i change the searching-fields to something other than "firstName" or "lastName" i dont get any results and no error.

```
var mongoose_fuzzy_searching = require('mongoose-fuzzy-searching');
const mongoose = require("mongoose");

var UserSchema = new mongoose.Schema({
    firstName: String,
    lastName: String,
    email: String,
    age: Number,
    jobName: String
});

UserSchema.plugin(mongoose_fuzzy_searching, {fields: ['jobName']});

var User = mongoose.model('fuzUser', UserSchema);

async function testFuzzy(){

    var user = new User({ firstName: 'Joe',  lastName: 'Doe', email: 'joe.doe@mail.com', age: 30, jobName:'carpenter'});
         await user.save(function () {console.log("saved") });
         await User.fuzzySearch('carpenter', function (err, users) {
            console.error(err);
            console.log("users: ", users);
       })
   
}
 testFuzzy();
```
Output is:

> saved
> null
> users:  []

Do you have any idea where my error is ?

**Comment by VassilisPallas** [comment]
Did you restart your application when you changed the `fields`? The plugin creates index for the selected fields, so maybe the indexes aren't set

**Comment by EliasPh** [comment]
Hey, thanks for the fast answer. Yes, i did restart die application. But it did not update the index. After deleting all indices and running the app again it works with the new fields like "job" etc. . Thanks!

**Comment by VassilisPallas** [comment]
You are welcome!
