### ISSUE TITLE
unaccurate search

### ISSUE THREAD

**Issue by Cobelt** [VassilisPallas/mongoose-fuzzy-searching#20]
Hello, I'm was looking for a fuzzy search before learning elasticsearch/lucene and then I found your plugin. But I'm having some really unaccurate results
Here is what I got for fuzzy fields:
  fields: [{
      name: 'name',
      minSize: 3,
      weight: 10,
  }
}]
(I did it like that just to try you plugin)

But with the plainText "mart" I'm getting items with field "name" that doesn't contain "mart" or similar (e.g : "Ceinture Noire de Frank Lee Bruce"), but it contains "mart" in other fields (e.g: description: "Célèbre combattant du dimanche, Frank s'est reconverti dans les arts **martiaux** après avoir lamentablement raté son diplôme de tailleur de pierres.")

So I tried to add the field description like that :
{
    name: 'description',
    minSize: 10,
    weight: 0
}
But "mart" is still returning the same data.

In my data i'm having a LOT of items with "marteau ...."

Am I doing something bad ? Did I missed something ?

Thanks a lot

**Comment by VassilisPallas** [comment]
Hello, for more accurate results add the [prefixOnly on initialization](https://github.com/VassilisPallas/mongoose-fuzzy-searching#object-keys) and also in [Model.fuzzySearch](https://github.com/VassilisPallas/mongoose-fuzzy-searching#fuzzysearch-parameters)
