### ISSUE TITLE
Specify an array field of strings

### ISSUE THREAD

**Issue by Capati** [VassilisPallas/mongoose-fuzzy-searching#27]
My document has an array field of strings that will be used as keywords or tags, currently this will trhow the error **`text.split` is not a function**, my quick fix was to check if `text` is an array and join the elements:

```javascript
 if (Array.isArray(text)) {
    if (text.length === 0) {
        return [];
    }
    text = text.join(' ');
}
```

**Comment by VassilisPallas** [comment]
Hi @Capati. Very interesting! I will create this feature on the next version!

**Comment by ratajgasper** [comment]
Hi! I just encountered the exact same problem. @Capati 's quick fix however helped. Thanks!

**Comment by juliushuck** [comment]
I had the same error (text.split is not a function). My problem was, that I accidentally tried to use a number field as a search field. Found this error, and maybe it helps somebody ✌️
