### ISSUE TITLE
Multiple pre-save hook issues

### ISSUE THREAD

**Issue by seeARMS** [VassilisPallas/mongoose-fuzzy-searching#28]
I have a pre-save hook that sets the value of 'this.contents' based on another field. Mongoose Fuzzy Search is set up to search based on 'this.contents'.

I think the pre-save hook that mongoose-fuzzy-searching requires to populate NGrams runs before the pre-save hook I created which populates 'this.contents'; therefore, no NGrams are populated.

Is there a way to specify which order the hooks run in? Can the mongoose-fuzzy-search middleware be post-save?

**Comment by seeARMS** [comment]
Changing my pre-save hook to a pre-validate hook fixed this issue.

**Comment by VassilisPallas** [comment]
Hi @seeARMS. Thanks for the feedback. I will try to add functionality to run something before the hooks in order to be easier to use the library
