### ISSUE TITLE
Return 'matched word' metadata with search results

### ISSUE THREAD

**Issue by seeARMS** [VassilisPallas/mongoose-fuzzy-searching#29]
It would be great if, after a fuzzy search is performed, some metadata is returned about what word was used to match. 

(The confidenceScore is returned, which is helpful, but it would be great if the search response also included the nGram / word with highest similarity to the input text).

**Comment by VassilisPallas** [comment]
Unfortunately mongoose $meta projection accepts only `textScore` for the $text projection. 
https://docs.mongodb.com/manual/reference/operator/projection/meta/

If I'm wrong please let me know!
