### ISSUE TITLE
Having some doubts about the created index and internal behaviour

### ISSUE THREAD

**Issue by TwireonEnix** [VassilisPallas/mongoose-fuzzy-searching#52]
Hi, I just installed your plugin and making some unit testing with my use case I have some troubles. Let's say I have the next basic schema:

```javascript
const articleSchema = new mongoose.Schema({
  title: {
    en: String,
    es: String,
  }
 // ... 
 otherProp: Boolean
}):
```

I want the fuzzy search to be in the two nested keys of the title, so I use the plugin according to your api: 

```javascript
articleSchema.plugin(fuzzySearch, {
  fields: [
    {
      name: 'title',
      keys: ['en', 'es'],
      minSize: 3
    }
  ]
});
```
Let's say i create the next document with title: 

```javascript
await new Article ({
  title: {
    en: 'This is an article title in english',
    es: 'A title that is supposed to be in spanish'
  }
},
// ...
).save();
```

After I check the database the n-grams are generated correctly and exist in the database. 
```javascript
 title_fuzzy: [
    {
      en_fuzzy: [
        'his',
        'thi',
        'this',
        'is',
        'an',
        'cle',
        'icl',
        'tic',
        'rti',
// ...
     ]
```
All cool, BUT when I did my testing, for example with the string 'cle' which is part of the n-grams array I have no results, not even when using more words, included in the n-gram array like: 'arti' or 'artic'. The only way I get results is by writing the whole word 'article' which afaik is the default behaviour of the native mongodb text search. 

While doing more debugging I printed the generated indexes and with surprise I saw that the text index is in the original field, this is the index object I get back:

```javascript
{
    v: 2,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'title.es_text_title.en_text',
    ns: 'LocalTest.articles',
    background: true,
    weights: { 'title.en': 1, 'title.es': 1 },
    default_language: 'english',
    language_override: 'language',
    textIndexVersion: 3
  }
```

Am I doing something wrong? Or why the index is not pointed to the generated n-gram arrays? If not, what's happening?

Also, is there any way to override the default language? In the docs, mongo can work with different languages.

Thank you in advance.

**Comment by TwireonEnix** [comment]
What I did to make it work is that I set the index manually after declaring the schema 

articleSchema.index({
  'title_fuzzy.es_fuzzy': 'text',
  'title_fuzzy.en_fuzzy': 'text'
});

Adding this the search work as I originally wanted. But again, was this necessary? Or what did I did wrong?

**Comment by VassilisPallas** [comment]
Hello, I will take a look because this is bizarre. In the meantime try to delete all the indices from your database to be created again.

**Comment by VassilisPallas** [comment]
Which version of the plugin are you using?

**Comment by TwireonEnix** [comment]
1.3.1. The default with npm i.

**Comment by dbads** [comment]
I too faced the same behaviour. The plugin seems not to be creating any index by itself.

**Comment by dbads** [comment]
Seems like we disabled, the auto index creation. Had to create text index manually. Stil I am not sure about why it creates an index like following - 
```
         "key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
```

**Comment by adrien-prototype** [comment]
@dbads would you help me on how create the indexes please ?

I'm stuck on this error when I try to do a fuzzy search : "MongoError: text index required for $text query" 

Here is my schema : 
``` 
const CoachingSchema = new Schema({
	title: {
		type: String,
		required: true,
		index: true
	},
	coachFirstName: {
		type: String,
		required: true,
		index: true
	},
	coachLastName: {
		type: String,
		required: true,
		index: true
	},
	coachUserName: {
		type: String,
		required: true,
		index: true
	},
	sport: {
		type: String,
		required: true,
		index: true
	}
})
```
And here's how I setup mongoose fuzzy searching :
```
CoachingSchema.plugin(mongooseFuzzySearching, {
	fields: [
		{
			name: 'coachUserName',
			weight: 3
		},
		{
			name: 'coachFirstName',
			weight: 2
		},
		{
			name: 'coachLastName',
			weight: 2
		},
		{
			name: 'sport',
			weight: 3
		},
		{
			name: 'title',
			weight: 2
		}
	]
})

I manually set the indexes according to this github issue : 

CoachingSchema.index({
	"coachUserName_fuzzy": "text",
	"coachFirstName_fuzzy": "text",
	"coachLastName_fuzzy": "text",
	"sport_fuzzy": "text",
	"title_fuzzy": "text"
})
```
Then I action the search from my route with a correct query :
```
const result = await Coaching.fuzzySearch(query).limit(20)
res.send(result)
```
That's how I get the index error. Would someone be able to hep me please ?? Would be super appreciated 🙌🏼
Thank you so much !!

**Comment by VassilisPallas** [comment]
I have tested that with `"mongoose": "^5.10.11"` and it works fine. I have made some minor (nonbreaking changes) and I'll publish the new version. 

Also bear in mind that you need to use `mongoose.set('useCreateIndex', true);` when connecting with the database according on this page: https://mongoosejs.com/docs/deprecations.html

**Comment by adrien-prototype** [comment]
My apologies in advance but I'm really stuck on that problem even though I'm very much trying.
I'm doing exactly the same thing on two models, on one it's working as expected, on the other not at all.

Here is the one it is not working with :

`
const mongoose = require('mongoose')
const Schema = mongoose.Schema
const mongoose_fuzzy_searching = require('mongoose-fuzzy-searching')

const CoachingSchema = new Schema(
	{
		title: {
			type: String,
			required: true,
			index: true
		},
		coachUserName: {
			type: String,
			required: true,
			index: true
		},
		sport: {
			type: String,
			required: true,
			index: true
		}
	},
	{
		autoIndex: true
	}
)

CoachingSchema.index({
	"coachUserName_fuzzy": "text",
	"sport_fuzzy": "text",
	"title_fuzzy": "text"
})

CoachingSchema.plugin(mongoose_fuzzy_searching, {
	fields: ['coachUserName', 'sport', 'title']
})

const Coaching = mongoose.model('coaching', CoachingSchema)
module.exports = Coaching
`

In the DB, it creates the following indexes : 
`
{
  "v": 2,
  "key": {
    "title": 1
  },
  "name": "title_1",
  "ns": "app.coachings",
  "background": true
},
{
  "v": 2,
  "key": {
    "coachUserName": 1
  },
  "name": "coachUserName_1",
  "ns": "app.coachings",
  "background": true
},
{
  "v": 2,
  "key": {
    "sport": 1
  },
  "name": "sport_1",
  "ns": "app.coachings",
  "background": true
},
`
When I search `result = await Coaching.fuzzySearch('some query') `I get the error I mentioned before :
`MongoError: text index required for $text query`

On the other hand I have this model : 
`
const mongoose = require('mongoose')
const Schema = mongoose.Schema
const mongoose_fuzzy_searching = require('mongoose-fuzzy-searching')

const UserSchema = new Schema(
	{
		firstName: {
			type: String,
			index: true
		},
		lastName: {
			type: String,
			index: true
		},
		userName: {
			type: String,
			unique: true,
			index: true
		}
	},
	{
		autoIndex: true
	}
)

UserSchema.index({
	"userName_fuzzy": "text",
	"firstName_fuzzy": "text",
	"lastName_fuzzy": "text"
})

UserSchema.plugin(mongoose_fuzzy_searching, {
	fields: ['userName', 'firstName', 'lastName']
})

const User = mongoose.model('user', UserSchema)
module.exports = User
`
This time it creates the same kind of indexes in my DB collection, but also another one added to the others automatically. It is quite different : 

`
{
  "v": 2,
  "key": {
    "_fts": "text",
    "_ftsx": 1
  },
  "name": "userName_fuzzy_text_firstName_fuzzy_text_lastName_fuzzy_text",
  "ns": "app.users",
  "background": true,
  "weights": {
    "firstName_fuzzy": 1,
    "lastName_fuzzy": 1,
    "userName_fuzzy": 1
  },
  "default_language": "english",
  "language_override": "language",
  "textIndexVersion": 3
}
`
Then when I search it is working as expected.
I'm using `"mongoose": "^5.10.11"`and `"mongoose-fuzzy-searching": ^1.3.4"`
I'm also using `mongoose.set('useCreateIndex', true);`according to what you said.

Any chance I might get some help here ? Thank you very very much 🙏

**Comment by VassilisPallas** [comment]
First of all, you don't need to create the indices by yourself, which mean you can remove these lines:

```
CoachingSchema.index({
	"coachUserName_fuzzy": "text",
	"sport_fuzzy": "text",
	"title_fuzzy": "text"
})
```

and 

```
UserSchema.index({
	"userName_fuzzy": "text",
	"firstName_fuzzy": "text",
	"lastName_fuzzy": "text"
})
```

Now the problem can be anything. Did you try to delete the indices and let the plugin to create them?

**Comment by adrien-prototype** [comment]
@VassilisPallas  thank you very much.

I guess I was blindfolded by going back and forth on that error. This was actually coming from a "language" field of type Array that I had on my model, which is a reserved word for mongoDB. The error wasn't very explicit but this was the cause.

I'm sorry that I reported it here and thank you again for the great work 💪🏽
All the best.
