### ISSUE TITLE
Format data before making ngrams 

### ISSUE THREAD

**Issue by Yhozen** [VassilisPallas/mongoose-fuzzy-searching#53]
**Do you want to request a _feature_, an _issue_, or report a _bug_?**
feature
**What is the current behaviour?**
Ngrams are created directly from data

**What is the expected behaviour?**
Having an option to format or parse data first

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**
For example, I want to search by date by writing the date in a certain format i.e: 'DD/MM/YYYY', therefore having an option to format the field as I like would be a really useful feature

I.E
```js
{
  name: 'date',
  format: date => dayjs(date).format('DD/MM/YYYY') 
}
```

I can work on this feature if we agree that is relevant and on how it's going to be implemented

**Comment by VassilisPallas** [comment]
Hi, I think you might need [middlewares](https://github.com/VassilisPallas/mongoose-fuzzy-searching#middlewares).

**Comment by Yhozen** [comment]
Thank you for your fast reply!

Correct me if I'm wrong, but I think I would need to write 6 middlewares as oppose to just write one function is that correct?

**Comment by VassilisPallas** [comment]
No, I think you need the [pre save middleware](https://mongoosejs.com/docs/middleware.html#pre). You can write something like this:

```javascript
  middlewares: {
    preSave: function() {
      this.date = dayjs(this.date).format('DD/MM/YYYY') 
    },
  }
```

Let me know if that helps. :)

**Comment by Yhozen** [comment]
It did! thank you!
