### ISSUE TITLE
No output except Query object

### ISSUE THREAD

**Issue by MisterPea** [VassilisPallas/mongoose-fuzzy-searching#55]
Hello,
So I have an issue that I can’t seem to track down.
Using your simple implementation: If I use promises, I get nothing. If I assign Model.fuzzySearch(…) to a variable and `console.log` the variable, I get a Query object that contains schema…collection name...search anagram etc. 
Below is the bit of code that spits out the Query object. A gist of the output is [here](https://gist.github.com/MisterPea/ed350b0b6fe66e097555e5cfe0f67617)
```javascript
const mongoose_fuzzy_searching = require('mongoose-fuzzy-searching');
const mongoose = require('mongoose')
const { Schema } = mongoose

const UserSchema = new Schema({
  firstName: String,
  lastName: String,
  email: String,
  age: Number,
});

UserSchema.plugin(mongoose_fuzzy_searching, { fields: ['firstName', 'lastName'] });

const User = mongoose.model('User', UserSchema);

const user = new User({ firstName: 'Joseph', lastName: 'Doe', email: 'joe.doe@mail.com', age: 30 });

try {
  user.save();
  const users = User.fuzzySearch('joe');
  console.log(users);

} catch (e) {
  console.error(e);
}
```
I tried an implementation on my atlas db-collection and got the same result. 
I’m not sure if I’m overlooking a dependency (I never got any errors), or if there’s an issue with the versions of node, mongoose. I'm not sure how to go about debugging this issue.
Software versions of pertinence: 
mongoose: 5.9.20
mongodb: 3.5.9
node: 14.4.0
mongoose-fuzzy-searching: 1.3.1

**Comment by rohit-gohri** [comment]
You'll have to either await the query object, call it's then method or pass a callback. Just like other Mongoose Query methods

**Comment by reading-stiener** [comment]
Hi there.. I am posting because I have similar issues. I tried the first example on a test database locally. When I make a fuzzy search, I get an empty list. I get no errors, so I'm not sure why. I did check the database and I can see the fuzzy fields get added to the data base. Here is my test code and my output in[ gist](https://gist.github.com/reading-stiener/c800df9dfe3ff1126c34af8ad878d94b). I am new to javascript, so I may have missed something while connecting to the database. 

````javascript
const mongooseFuzzySearching = require('mongoose-fuzzy-searching');
var mongoose  = require('mongoose')


mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true, useUnifiedTopology: true});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
    const UserSchema = new mongoose.Schema({
      firstName: String,
      lastName: String,
      email: String,
      age: Number,
    });
    
    UserSchema.plugin(mongooseFuzzySearching, { fields: ['firstName', 'lastName'] });
    
    const User = mongoose.model('User', UserSchema);
    
    const user = new User({ firstName: 'Joe', lastName: 'Doe', email: 'joe.doe@mail.com', age: 30 });
    (async () => { 
        try {
            //await user.save(); // mongodb: { ..., firstName_fuzzy: [String], lastName_fuzzy: [String] }
            users = await User.fuzzySearch({ query: 'jo' })
            console.log(users);
            //console.log(users);
            // each user object will not contain the fuzzy keys:
            // Eg.
            // {
            //   "firstName": "Joe",
            //   "lastName": "Doe",
            //   "email": "joe.doe@mail.com",
            //   "age": 30,
            //   "confidenceScore": 34.3 ($text meta score)
            // }
          } catch (e) {
            console.error(e);
          }
    })();   
})
```

Dependencies
 "mongoose": "^5.9.20",
 "mongoose-fuzzy-searching": "^1.3.1"
