### ISSUE TITLE
Any way to use projections on the fuzzySearch function?

### ISSUE THREAD

**Issue by ramtinsoltani** [VassilisPallas/mongoose-fuzzy-searching#59]
**Do you want to request a _feature_, an _issue_, or report a _bug_?**
New feature

**What is the current behaviour?**
`Model.fuzzySearch()` doesn't provide projections.

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
To accept projections through `Model.fuzzySearch()` parameters.

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**
Makes the API more in-line with Mongoose API and results in less repetitive and cleaner code.

**Please mention other relevant information such as Node.js and mongoose version.**
Node: 12.13.1
Mongoose: 5.9.25

**Comment by VassilisPallas** [comment]
Could you please share an example? The reason I'm asking that is that this works very well:

```javascript
const users = await User.fuzzySearch("art").select({ name: 1, _id: 0 });
```
Is it what you are looking for?

**Comment by ramtinsoltani** [comment]
Thank you, that's it.
