### ISSUE TITLE
does it support arabic?

### ISSUE THREAD

**Issue by mohamadelhinamy** [VassilisPallas/mongoose-fuzzy-searching#66]

**Comment by VassilisPallas** [comment]
No, but you can contribute by adding in this array any Arabic letters to be converted into the Latin alphabet -> https://github.com/VassilisPallas/mongoose-fuzzy-searching/blob/4f447cd3bbe5dc32ad221248937856b80ecbc32e/helpers/languageCharacters.js#L1-L80
