### ISSUE TITLE
TypeError: obj.fromObjectKeys is not a function

### ISSUE THREAD

**Issue by DonTsipa** [VassilisPallas/mongoose-fuzzy-searching#68]
const mongoose = require('mongoose');
const mongooseFuzzySearching = require('mongoose-fuzzy-searching');
const updateFuzzy = require('../lib/updateModel');

/*  const mongoosastic = require('mongoosastic');
const esClient = require('../searchConnection'); */

const RecipeSchema = mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  category: {
    type: mongoose.ObjectId,
    ref: 'RecipeCategory',
  },
  tags: [{
    family: {
      type: String,
      required: true,
    },
    title: {
      type: String,
    },
  }],
  previewImg: {
    type: String,
    required: true,
  },
  likes: {
    type: Number,
    default: 0,
  },
  time: {
    type: Number,
    default: 0,
  },
  portions: {
    type: Number,
    default: 1,
  },
  comments: [{
    type: mongoose.ObjectId,
    ref: 'Comment',
  }],
  products: [{
    product: {
      type: mongoose.ObjectId,
      ref: 'Product',
    },
    value: {
      type: Number,
      default: 0,
    },
    valueType: { // 'volume', 'weight', 'count'
      type: String,
      default: 'count',
    },
    measureObj: {
      measuringInstrument: {
        type: mongoose.ObjectId,
        ref: 'MeasuringInstrument',
      },
      count: {
        type: Number,
        default: 0,
      },
    },
  }],
  steps: [{
    source: {
      type: String,
    },
    type: {
      type: String,
    },
    start: {
      type: String,
    },
    end: {
      type: String,
    },
    text: {
      type: String,
      required: true,
    },
  }],
  active: {
    type: Boolean,
    default: true,
  },
});

RecipeSchema.plugin(mongooseFuzzySearching, {
  fields: [{
    name: 'title',
    minSize: 5,
  },
  {
    name: 'tags',
    keys: ['title'],
  },
  ],
});

Getting the error "TypeError: obj.fromObjectKeys is not a function" when adding some objects or trying to work with pre-existing data or tryng to search something
Though, fuzzy objects are created o_O

**Comment by DonTsipa** [comment]
Fixed it by adding method
  fromObjectKeys(item) {
    delete this.schema[`${item.name}_fuzzy`];
  }

to Remove class, but it still doesn't search, using tags__fuzzy field

**Comment by TwireonEnix** [comment]
This happens to me as well but when populating another document with references to the collection with the fuzzy searching applied. 

Silly Example
Socks (searchable with the plugin) and Drawers Collections (not searchable)

const aDrawer = await Drawer.create({ oneSock: someIdForSock });

aDrawer.populate('oneSock').execPopulate(); // error

and this is the call stack 

TypeError: obj.fromObjectKeys is not a function
node_modules/mongoose-fuzzy-searching/helpers/db/fields.js:117:9
    at Array.forEach (<anonymous>)

**Comment by TheJoshE** [comment]
It looks like there's already a PR to fix this it's just waiting to be merged: https://github.com/VassilisPallas/mongoose-fuzzy-searching/pull/63

@VassilisPallas  Any chance of this getting merged in?
