### ISSUE TITLE
Cannot find some string values

### ISSUE THREAD

**Issue by egonzal93** [VassilisPallas/mongoose-fuzzy-searching#79]
--When I search for 'ano' I get this:
Mongoose: tasks.find({ '$text': { '$search': 'no an ano' } }, { projection: {} })
Mongoose: tasks.find({ '$text': { '$search': 'no an ano' } }, { projection: {} })
  search **Yet Another Completely unrelated name** +0ms
  search **Another Completely unrelated name** +0ms

--With 'another, I get these hits:

Mongoose: tasks.find({ '$text': { '$search': 'er he th ot no an her the oth not ano ther othe noth anot other nothe anoth nother anothe another' } }, { projection: {} })
Mongoose: tasks.find({ '$text': { '$search': 'er he th ot no an her the oth not ano ther othe noth anot other nothe anoth nother anothe another' } }, { projection: {} })
  search **Yet Another Completely unrelated name** +0ms
  search **Another Completely unrelated name** +0ms

--Searching for 'ye', I get hits:
Mongoose: tasks.find({ '$text': { '$search': 'ye' } }, { projection: {} })
Mongoose: tasks.find({ '$text': { '$search': 'ye' } }, { projection: {} })
  search **Yet Another Completely unrelated name** +0ms

**--Searching for 'an', I don't get any hits:**

--But when I search 'an' I do not get any hit:
Mongoose: tasks.find({ '$text': { '$search': 'an' } }, { projection: {} })
Mongoose: tasks.find({ '$text': { '$search': 'an' } }, { projection: {} })

**How come 'an' is not found and yet 'ye' was found?**

**Not using fuzzySearch() seemed to work, I can get hits for 'an'**

 const queryOverride = {     
        '$or':
            [
                {'info_fuzzy.name1_fuzzy': {'$regex': `^${searchValue}`}},
                {'info_fuzzy.title_fuzzy': {'$regex': `^${searchValue}`}},
                {'info_fuzzy.version_fuzzy': {'$regex': `^${searchValue}`}},
                {'info_fuzzy.description_fuzzy': {'$regex': `^${searchValue}`}}
            ]
    }
    const results = await Task
        .find(queryOverride)
        // .fuzzySearch(searchValue)
        .exec();

Mongoose: tasks.find({ '$or': [ { 'info_fuzzy.name1_fuzzy': { '$regex': '^an' } }, { 'info_fuzzy.title_fuzzy': { '$regex': '^an' } }, { 'info_fuzzy.version_fuzzy': { '$regex': '^an' } }, { 'info_fuzzy.description_fuzzy': { '$regex': '^an' } } ] }, { projection: {} })
Mongoose: tasks.createIndex({ 'info_fuzzy.name1_fuzzy': 'text', 'info_fuzzy.title_fuzzy': 'text', 'info_fuzzy.version_fuzzy': 'text', 'info_fuzzy.description_fuzzy': 'text' }, { weights: {}, name: 'fuzzy_text', background: true })
  search Army of Ants +0ms
  search Army Ants +0ms
  search Ant Man +0ms
  search Another Completely unrelated name +0ms
  search Yet Another Completely unrelated name +1ms

**************
Heres my schema:

const mongoose = require('mongoose');
const mongoose_fuzzy_searching = require('mongoose-fuzzy-searching');

const taskSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
    environment: {
        type: String,
        required: true
    },
  info: {
    name1: String,
    title: String,
    version: String,
    description: String
  },
  completed: {
    type: Boolean,
    required: true
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
    timestamps: true
});

// NOTE: Index need to be dropped and re-created each time fields are updated
taskSchema.plugin( mongoose_fuzzy_searching, {
    fields: [
        // {
        //     name: 'name',
        //     minSize: 1,
        //     prefixOnly: false,
        // },
        {
            name: 'info',
            minSize: 2,
            prefixOnly: false,
            keys: [
                'name1',
                'title',
                'version',
                'description'
            ]
        }
    ]
    }
);

module.exports = mongoose.model('Task', taskSchema);

**Comment by VassilisPallas** [comment]
Can you please write your question better?
Also, try to wrap your code in code blocks.

**Comment by egonzal93** [comment]
I apologize my question is not clear and is not organized. I did not use code blocks in evaluating mongoose-fuzzy-searching because I don't want to include actual the GraphQL server code where fuzzy search will be implemented implemented inside the code block.  

It worked using $regex however I can get a hit with just 'a', 'an'

query['$or'] = [
                    {'info_fuzzy.name1_fuzzy':  {'$regex': `^${searchValue}`}},
                    {'info_fuzzy.title_fuzzy' : {'$regex': `^${searchValue}`}},
                    {'info_fuzzy.version_fuzzy': {'$regex': `^${searchValue}`}},
                    {'info_fuzzy.description_fuzzy': {'$regex': `^${searchValue}`}}
                ];
