### ISSUE TITLE
update to mongoose 6.x.x

### ISSUE THREAD

**Issue by imranbarbhuiya** [VassilisPallas/mongoose-fuzzy-searching#98]
**Do you want to request a _feature_, an _issue_, or report a _bug_?**
yes
**What is the current behaviour?**
I can't install it with mongoose 6.x.x normally.
**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
It should have mongoose 6.x.x included in peer dependency
**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

**Please mention other relevant information such as Node.js and mongoose version.**
node js 16.13.0
mongoose 6.0.12

**Comment by imranbarbhuiya** [comment]
@VassilisPallas please check these issues.

**Comment by Meffesino** [comment]
I can only second that... Would be awesome if it could run with mongoose 6.x

**Comment by TwireonEnix** [comment]
It's been a year since the last time the package updated. I'm afraid the project is dead. Which is a shame because it has been useful to me. I guess the alternative is for someone else to fork it and keep maintaining it.

**Comment by imranbarbhuiya** [comment]
https://github.com/imranbarbhuiya/mongoose-fuzzy-searching

I've created this for my personal use. Anyone who wants to use/contribute, are welcome.
